#pragma config(Motor,  motorA,          leftMotor,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,         tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 *  Moves the robot based on Joystick values.
 */

#include "JoystickDriver.c"

task main() {
  // Keep running this code
  while(true) {
    // Check to see if there are any updates
    getJoystickSettings(joystick);

    // Set the motor values based on joystick position
    motor[leftMotor] = joystick.joy1_y1;
    motor[rightMotor] = joystick.joy2_y2;

    wait1Msec(20);
  }
}
