#pragma config(Motor,  motorA,          leftMotor,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,         tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 *  Moves the robot based on Joystick values.
 */

#include "JoystickDriver.c"

task main() {
  // Keep running this code
  while(true) {
    // Check to see if there are any updates
    getJoystickSettings(joystick);

    // Store joystick values
    int leftMotorValue = joystick.joy1_y1;
    int rightMotorValue = joystick.joy1_y2;

    // Adjust for joystick offset
    if(abs(leftMotorValue) < 20) {
      leftMotorValue = 0;
    }

    if(abs(rightMotorValue) < 20) {
      rightMotorValue = 0;
    }

    motor[leftMotor] = leftMotorValue;
    motor[rightMotor] = rightMotorValue;

    wait1Msec(20);
  }
}
