#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 *  Moves the robot based on Joystick values.
 */

#include "JoystickDriver.c"

task main() {
  // Keep running this code
  while(true) {
    // Check to see if there are any updates
    getJoystickSettings(joystick);

    // Store joystick values
    int leftMotorValue = joystick.joy1_y1;
    int rightMotorValue = joystick.joy1_y2;

    // Adjust for joystick offset
    if(abs(leftMotorValue) < 20) {
      leftMotorValue = 0;
    }

    if(abs(rightMotorValue) < 20) {
      rightMotorValue = 0;
    }

    motor[leftMotor] = leftMotorValue;
    motor[rightMotor] = rightMotorValue;

    wait1Msec(20);
  }
}
