#pragma config(Sensor, S1,     touch,               sensorTouch)
#pragma config(Motor,  motorA,          leftMotor,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 *  Moves the robot forward at full speed until a touch
 *  sensor is pressed.
 */

task main() {
  // Start the motors
  motor[leftMotor] = 100;
  motor[rightMotor] = 100;

  // Keep waiting until the button is pressed
  while(SensorValue(touch) != 1) {
    wait1Msec(50);
  }

  // Stop the motors
  motor[leftMotor] = 0;
  motor[rightMotor] = 0;
}
