#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S4,     Billy,          sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Line Follower


task main()
{
	while(true) {
		writeDebugStreamLine("Light value is : %d", SensorValue[Billy]);
		if(SensorValue[Billy] > 30) {
			motor[motorD] = 100;
			motor[motorE] = 0;
		}
		else if(SensorValue[Billy] < 30) {
			motor[motorE] = 100;
			motor[motorD] = 0;
		}
		wait1Msec(20);
	}
}
