#pragma config(Sensor, S1,     light,               sensorLightActive)
#pragma config(Motor,  motorA,          leftMotor,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 *  Moves the robot forward at full speed until a touch
 *  sensor is pressed.
 */

task main() {
  // Start the motors
	motor[leftMotor] = 100;
	motor[rightMotor] = 100;

	// Keep waiting until the light sensor
	// returns a value greater than 45.
	while(SensorValue(light) <= 45) {
		wait1Msec(50);
	}

	// Stop the motors
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}
