#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int i = 0;
	while(i < 10) {					// Repeat while i is less than 10
		motor(motorD) = 100;
		motor(motorE) = 100;
		wait1Msec(1000);
		motor(motorD) = 100;
		motor(motorE) = 100;
		wait1Msec(1000);
		i ++;
	}
}
