#pragma config(Motor,  motorA,          leftMotor,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,         tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 *  Moves the robot backward at full speed for two seconds.
 */

task main() {
  // Start the motors in reverse
	motor[leftMotor] = -100;
	motor[rightMotor] = -100;

	wait1Msec(2000); // Pause two seconds

	// Stop the motors
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}
