#pragma config(Motor,  motorA,          leftMotor,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,         tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 *  Moves the robot forward at full speed for two seconds.
 */

void startMotors() {
  motor[leftMotor] = 100;
  motor[rightMotor] = 100;
}

void stopMotors() {
  motor[leftMotor] = 0;
  motor[rightMotor] = 0;
}

task main() {
  // Start the motors
  startMotors();

  wait1Msec(2000); // Pause two seconds

  // Stop the motors
  stopMotors();
}
