#pragma config(Sensor, S1,     light,               sensorLightActive)
#pragma config(Motor,  motorA,          leftMotor,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 *  Calls a custom function to check the value of a light sensor.
 *  Stops the robot when that function returns true.
 */


bool checkLightSensor() {
  if(SensorValue(light) <= 45) {
    return true;
  }else {
    return false;
  }
}

task main() {
  // Start the motors
  motor[leftMotor] = 100;
  motor[rightMotor] = 100;

  // Keep waiting until checkLightSensor() returns true.
  while(checkLightSensor()) {
    wait1Msec(50);
  }

  // Stop the motors
  motor[leftMotor] = 0;
  motor[rightMotor] = 0;
}
