#pragma config(Motor,  motorA,          leftMotor,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,         tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 *  Moves the robot forward at full speed for two seconds.
 */

void setMotors(int speed) {
  motor[leftMotor] = speed;
  motor[rightMotor] = speed;
}

task main() {
  // Start the motors
  setMotors(100);

  wait1Msec(2000); // Pause two seconds

  // Stop the motors
  setMotors(0);
}
