#pragma config(Motor,  motorA,          leftMotor,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,         tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 *  Moves forward for two seconds, but waits for start first.
 */

task main() {
  // Insert any necessary setup here.

  waitForStart(); // Wait until the match begins.

  // Start the motors
  motor[leftMotor] = 100;
  motor[rightMotor] = 100;

  wait1Msec(2000); // Pause two seconds

  // Stop the motors
  motor[leftMotor] = 0;
  motor[rightMotor] = 0;
}
